baseURL = "https://laughing-minsky-fae602.netlify.app"
languageCode = "en-us"
title = "JAMsite"
theme = "tale"
copyright = "Copyright 2020 moiova.tv"
disableKinds = ["section"]

[outputs]
  home = ["HTML", "JSON"]
